# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x12\x04post\"\x1e\n\x0bPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\"\"\n\rUserNameReply\x12\x11\n\tuser_name\x18\x01 \x01(\t\"\x1f\n\x0ePostTitleReply\x12\r\n\x05title\x18\x01 \x01(\t2y\n\x07Greeter\x12\x37\n\x0bGetUserName\x12\x11.post.PostRequest\x1a\x13.post.UserNameReply\"\x00\x12\x35\n\x08GetTitle\x12\x11.post.PostRequest\x1a\x14.post.PostTitleReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTREQUEST']._serialized_start=20
  _globals['_POSTREQUEST']._serialized_end=50
  _globals['_USERNAMEREPLY']._serialized_start=52
  _globals['_USERNAMEREPLY']._serialized_end=86
  _globals['_POSTTITLEREPLY']._serialized_start=88
  _globals['_POSTTITLEREPLY']._serialized_end=119
  _globals['_GREETER']._serialized_start=121
  _globals['_GREETER']._serialized_end=242
# @@protoc_insertion_point(module_scope)
