"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PostRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POST_ID_FIELD_NUMBER: _builtins.int
    post_id: _builtins.int
    def __init__(
        self,
        *,
        post_id: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["post_id", b"post_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PostRequest: _TypeAlias = PostRequest  # noqa: Y015

@_typing.final
class UserNameReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USER_NAME_FIELD_NUMBER: _builtins.int
    user_name: _builtins.str
    def __init__(
        self,
        *,
        user_name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["user_name", b"user_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UserNameReply: _TypeAlias = UserNameReply  # noqa: Y015

@_typing.final
class PostTitleReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PostTitleReply: _TypeAlias = PostTitleReply  # noqa: Y015
