"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import post_pb2 as _post_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class GreeterStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> GreeterAsyncStub: ...
    GetUserName: _grpc.UnaryUnaryMultiCallable[_post_pb2.PostRequest, _post_pb2.UserNameReply]
    GetTitle: _grpc.UnaryUnaryMultiCallable[_post_pb2.PostRequest, _post_pb2.PostTitleReply]

@_typing.type_check_only
class GreeterAsyncStub(GreeterStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetUserName: _aio.UnaryUnaryMultiCallable[_post_pb2.PostRequest, _post_pb2.UserNameReply]  # type: ignore[assignment]
    GetTitle: _aio.UnaryUnaryMultiCallable[_post_pb2.PostRequest, _post_pb2.PostTitleReply]  # type: ignore[assignment]

class GreeterServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetUserName(
        self,
        request: _post_pb2.PostRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_post_pb2.UserNameReply, _abc.Awaitable[_post_pb2.UserNameReply]]: ...

    @_abc_1.abstractmethod
    def GetTitle(
        self,
        request: _post_pb2.PostRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_post_pb2.PostTitleReply, _abc.Awaitable[_post_pb2.PostTitleReply]]: ...

def add_GreeterServicer_to_server(servicer: GreeterServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
